import fs from "fs";

const filePath = "src/data/vsData.ts";
let data = fs.readFileSync(filePath, "utf-8");

// Targeted replacements for remaining English words
// Operates only within passiveDesc and unlock strings
const fieldReplacements = [
  // Common nouns
  [/\bevolution\b/gi, '进化'],
  [/\bevolutions?\b/gi, '进化'],
  [/\bfreeze\b/gi, '冰冻'],
  [/\bvacuum\b/gi, '真空'],
  [/\bsprites?\b/gi, '精灵'],
  [/\btongue\b/gi, '舌头'],
  [/\btongues?\b/gi, '舌头'],
  [/\btechs?\b/gi, '科技'],
  [/\bboost\b/gi, '加成'],
  [/\bremainder\b/gi, '剩余'],
  [/\bprobability\b/gi, '概率'],
  [/\bchance\b/gi, '几率'],

  // Verbs/adjectives
  [/\brolled\b/gi, '掷出'],
  [/\blessened\b/gi, '减少'],
  [/\brespectively\b/gi, '分别'],
  [/\badditional\b/gi, '额外'],
  [/\bregardless\b/gi, '无论'],
  [/\bcritically\b/gi, '严重'],
  [/\bfixed\b/gi, '固定'],
  [/\badditively\b/gi, '累加'],
  [/\brarely\b/gi, '很少'],
  [/\bdepreciates?\b/gi, '衰减'],

  // Common words
  [/\bequal\b/gi, '等于'],
  [/\bproportion\b/gi, '比例'],
  [/\bmissing\b/gi, '缺失'],
  [/\bextra\b/gi, '额外'],
  [/\bobtaining\b/gi, '获得'],
  [/\bmultiply\b/gi, '乘以'],
  [/\bmultiplies\b/gi, '乘以'],
  [/\bhowever\b/gi, '然而'],

  // Number words
  [/\bone\b/gi, '一个'],
  [/\beight\b/gi, '八'],
  [/\bzero\b/gi, '零'],

  // Possessive 's
  [/('|\u2019)s\s+initial/g, '的初始'],
  [/('|\u2019)s\b/g, '的'],

  // 'is' contraction
  [/\bis\b/gi, '是'],

  // Game terms
  [/\bat\s+all\b/gi, '完全'],
  [/\bstart\s+game\s+with\b/gi, '以'],
  [/\bcompletely\b/gi, '完全'],
  [/\bdoes\s+not\s+start\b/gi, '不'],
  [/\bfrom\s+light\s+sources\b/gi, '从光源'],
  [/\bthat\s+is\b/gi, '即'],
  [/\bthat\s+are\b/gi, '即'],
  [/\bas\s+a\s+follower\b/gi, '作为随从'],
  [/\blight\s+sources?\b/gi, '光源'],

  // Proper names (in descriptions)
  [/\bSanta\b/g, '圣诞老人'],
  [/\bHuge\s+Trouble\b/g, '大麻烦'],
  [/\bTorino\b/g, '托里诺'],
  [/\bLuminaire\b/g, '路米奈尔'],
  [/\bPako\s+Battiliar\b/g, '帕科·巴蒂利亚'],
  [/\bPenshin\s+Fatcha\b/g, '彭申·法查'],
  [/\bLavatrix\s+Machina\b/g, '拉瓦特里克斯·马奇纳'],
  [/\bAcquazzone\b/g, '阿夸佐内'],
  [/\bShowstopper\b/g, '压轴表演'],
  [/\bGlass\s+Fandango\b/g, '玻璃凡丹戈'],
  [/\bSanta\s+Javelin\b/g, '圣诞标枪'],
  [/\bMagi\s+Stone\b/g, '魔法石'],
  [/\bBlood\s+Chalice\b/g, '血杯'],
  [/\bPhotonstorm\b/g, '光子风暴'],
  [/\bGlaive\b/g, '刃枪'],
  [/\bThe\s+Lycaeum\b/g, '讲堂'],
  [/\bThe\s+Laborratory\b/g, '实验室'],

  // --- batch: extensive remaining words ---
  // Game nouns
  [/\btimer\b/gi, '计时器'],
  [/\bcamera\b/gi, '镜头'],
  [/\btext\b/gi, '文字'],
  [/\bcircles?\b/gi, '圆圈'],
  [/\bsize\b/gi, '大小'],
  [/\bconditions?\b/gi, '条件'],
  [/\bterrain\b/gi, '地形'],
  [/\bwalls?\b/gi, '墙壁'],
  [/\bobstacles?\b/gi, '障碍'],
  [/\bgaps?\b/gi, '间隙'],
  [/\bgate\b/gi, '大门'],
  [/\bgems?\b/gi, '宝石'],
  [/\bdeck\b/gi, '牌组'],
  [/\binstance\b/gi, '实例'],
  [/\blist\b/gi, '列表'],
  [/\bdecimal\b/gi, '十进制'],
  [/\blogarithm\b/gi, '对数'],
  [/\bstacks?\b/gi, '叠加'],
  [/\bedition\b/gi, '版本'],
  [/\bbase\b/gi, '基数'],
  [/\britual\b/gi, '仪式'],
  [/\bratio\b/gi, '比率'],
  [/\bthresholds?\b/gi, '阈值'],
  [/\bpositions?\b/gi, '位置'],
  [/\bmodifier\b/gi, '修饰器'],
  [/\bway\b/gi, '方式'],
  [/\btiles?\b/gi, '地块'],
  [/\bnumbers?\b/gi, '数字'],
  [/\bmoment\b/gi, '时刻'],
  [/\bstate\b/gi, '状态'],
  [/\bwalks?\b/gi, '行走'],

  // Color words
  [/\bgreen\b/gi, '绿色'],
  [/\bblue\b/gi, '蓝色'],
  [/\bred\b/gi, '红色'],
  [/\bwhite\b/gi, '白色'],
  [/\bblack\b/gi, '黑色'],
  [/\bgolden\b/gi, '金色'],
  [/\bsilver\b/gi, '银色'],

  // Verbs
  [/\brolling\b/gi, '掷出'],
  [/\bimpact\b/gi, '影响'],
  [/\boscillating\b/gi, '振荡'],
  [/\bconverted\b/gi, '转换'],
  [/\bconsumed\b/gi, '消耗'],
  [/\bcollected\b/gi, '收集'],
  [/\bcollects?\b/gi, '收集'],
  [/\bdies\b/gi, '死亡'],
  [/\bleave\b/gi, '离开'],
  [/\bleaves\b/gi, '离开'],
  [/\bretreats?\b/gi, '撤退'],
  [/\bregenerate\b/gi, '再生'],
  [/\bregenerates?\b/gi, '再生'],
  [/\bopens?\b/gi, '打开'],
  [/\bopened\b/gi, '打开'],
  [/\bcomes?\b/gi, '回来'],
  [/\bmorphing\b/gi, '变形'],
  [/\btotaling\b/gi, '总计'],
  [/\bflies\b/gi, '飞行'],
  [/\bfinding\b/gi, '发现'],
  [/\bspawning\b/gi, '生成'],
  [/\bdrafting\b/gi, '选取'],
  [/\bkilling\b/gi, '击杀'],
  [/\babouts?\b/gi, '大约'],
  [/\bcontain\b/gi, '包含'],
  [/\bcontains?\b/gi, '包含'],
  [/\bpossesses?\b/gi, '拥有'],
  [/\bpossess\b/gi, '拥有'],
  [/\bcosting\b/gi, '消耗'],
  [/\bcosts?\b/gi, '消耗'],
  [/\bmust\b/gi, '必须'],
  [/\bunlock\b/gi, '解锁'],
  [/\bunlocks?\b/gi, '解锁'],
  [/\bunlocking\b/gi, '解锁'],
  [/\bequipping\b/gi, '装备'],
  [/\brequiring\b/gi, '需要'],
  [/\brecheck\b/gi, '重新检视'],
  [/\bsubtract\b/gi, '减去'],
  [/\bsubtracted\b/gi, '减去'],
  [/\bdelayed\b/gi, '延迟'],
  [/\blocated\b/gi, '位于'],
  [/\bdivided\b/gi, '除以'],
  [/\boverheal\b/gi, '过量治疗'],
  [/\boverhealed\b/gi, '过量治疗'],
  [/\baccumulate\b/gi, '累积'],
  [/\baccumulated\b/gi, '累积'],
  [/\bboost\b/gi, '强化'],
  [/\bboosted\b/gi, '强化'],
  [/\berase\b/gi, '抹除'],
  [/\berased\b/gi, '抹除'],
  [/\bprevent\b/gi, '防止'],
  [/\bprevents?\b/gi, '防止'],
  [/\bhurry\b/gi, '加速'],
  [/\bkill\b/gi, '击杀'],
  [/\bwalk\b/gi, '行走'],
  [/\bwalking\b/gi, '行走'],
  [/\bchecks?\b/gi, '检视'],
  [/\bchecked\b/gi, '检视'],
  [/\bmeans?\b/gi, '意味着'],
  [/\bforges?\b/gi, '锻造'],
  [/\bneither\b/gi, '也非'],

  // Adjectives/adverbs
  [/\btowards\b/gi, '朝向'],
  [/\bvice\s+versa\b/gi, '反之亦然'],
  [/\bactual\b/gi, '实际'],
  [/\bthemselves\b/gi, '自身'],
  [/\bboth\b/gi, '两者'],
  [/\bunited\b/gi, '联合'],
  [/\busual\b/gi, '通常'],
  [/\bnormal\b/gi, '正常'],
  [/\bproper\b/gi, '正确'],
  [/\balternate\b/gi, '替代'],
  [/\bautomatically\b/gi, '自动'],
  [/\baccordance\b/gi, '根据'],
  [/\bseveral\b/gi, '若干'],
  [/\binvulnerable\b/gi, '无敌'],
  [/\bindependent\b/gi, '独立'],
  [/\brapidly\b/gi, '快速'],
  [/\bat\s+least\b/gi, '至少'],
  [/\binside\b/gi, '内部'],
  [/\boutside\b/gi, '外部'],
  [/\baround\b/gi, '周围'],
  [/\bsince\b/gi, '此后'],
  [/\bexcept\b/gi, '除了'],
  [/\bwhether\b/gi, '是否'],
  [/\bunlike\b/gi, '不像'],
  [/\bfeatured\b/gi, '特色'],

  // Pronouns/quantifiers/etc
  [/\beither\b/gi, '或'],
  [/\blike\b/gi, '如'],
  [/\btop\b/gi, '顶部'],
  [/\breal\b/gi, '实际'],
  [/\bremains?\b/gi, '保留'],
  [/\bmoving\b/gi, '移动'],
  [/\bnear\b/gi, '附近'],
  [/\badding\b/gi, '加上'],
  [/\badded\b/gi, '加上'],
  [/\bnorth\b/gi, '北'],
  [/\bsouth\b/gi, '南'],
  [/\beast\b/gi, '东'],
  [/\bwest\b/gi, '西'],
  [/\bdefault\b/gi, '默认'],
  [/\bmaxed\b/gi, '满级'],
  [/\bstarts?\b/gi, '开始'],

  // Special items/names
  [/\bGolden\s+Eggs?\b/g, '金蛋'],
  [/\bQuincy\b/g, '昆西'],
  [/\bBelnades\b/g, '贝尔纳德斯'],
  [/\bSpellbook\b/g, '魔法书'],
  [/\bShaft\b/g, '竖井'],
  [/\bBloody\s+Tear\b/g, '血泪'],

  // direction compounds
  [/\bnorth\b/gi, '北'],
  [/\bsouth\b/gi, '南'],
  [/\beast\b/gi, '东'],
  [/\bwest\b/gi, '西'],

  // --- final catch batch ---
  [/\bactive\b/gi, '生效'],
  [/\bgame\b/gi, '游戏'],
  [/\btotal\b/gi, '总共'],
  [/\bupgraded\b/gi, '升级'],
  [/\bstarting\b/gi, '开始'],
  [/\bbats\b/gi, '蝙蝠'],
  [/\bDracula\b/g, '德古拉'],
  [/\bNathan\b/g, '内森'],
  [/\bEgo\b/g, '伊戈'],
  [/\bbee\b/gi, '蜜蜂'],
  [/\bbees?\b/gi, '蜜蜂'],
  [/\bchamber\b/gi, '房间'],
  [/\bnamely\b/gi, '即'],
  [/\bSurvarot\b/gi, '苏瓦罗'],
  [/\bSurvarots?\b/gi, '苏瓦罗'],
  [/\bsmall\b/gi, '小'],
  [/\bsingle\b/gi, '单个'],
  [/\bitems?\b/gi, '物品'],
  [/\bactivation\b/gi, '激活'],
  [/\bMoon\b/gi, '月'],
  [/\bleast\b/gi, '至少'],
  [/\blimit\b/gi, '限制'],
  [/\bthus\b/gi, '因此'],
  [/\brange\b/gi, '范围'],
  [/\bleveling\b/gi, '升级'],
  [/\brevived\b/gi, '复活'],
  [/\bdrop\b/gi, '掉落'],
  [/\balready\b/gi, '已经'],
  [/\bcontact\b/gi, '接触'],
  [/\btake\b/gi, '获取'],
  [/\btaken\b/gi, '获取'],
  [/\bprovide\b/gi, '提供'],
  [/\bprovided\b/gi, '提供'],
  [/\bhaving\b/gi, '拥有'],
  [/\btwo\b/gi, '两'],
  [/\bthree\b/gi, '三'],
  [/\bfour\b/gi, '四'],
  [/\bbirds?\b/gi, '鸟'],
  [/\bbreak\b/gi, '打破'],
  [/\bextension\b/gi, '延长'],
  [/\blost\b/gi, '丢失'],
  [/\bfunctions?\b/gi, '功能'],
  [/\ballowing\b/gi, '允许'],
  [/\brings?\b/gi, '戒指'],
  [/\bexample\b/gi, '例如'],
  [/\beggs?\b/gi, '蛋'],
  [/\bdisco\b/gi, '迪斯科'],
  [/\bbringing\b/gi, '带来'],
  [/\bnegating\b/gi, '消除'],
  [/\bpenalties?\b/gi, '惩罚'],
  [/\bretaliate\b/gi, '反击'],
  [/\bplayable\b/gi, '可玩'],
  [/\bversions?\b/gi, '版本'],
  [/\bextends?\b/gi, '延长'],
  [/\bstopping\b/gi, '停止'],
  [/\bvolley\b/gi, '齐射'],
  [/\bper\b/gi, '每'],
  [/\bused\b/gi, '使用'],
  [/\binvincibility\b/gi, '无敌'],
  [/\bbecoming\b/gi, '变成'],
  [/\binvincible\b/gi, '无敌'],
  [/\bturning\b/gi, '变为'],
  [/\beat\b/gi, '吃'],
  [/\beaten\b/gi, '吃掉'],
  [/\bletting\b/gi, '让'],
  [/\bbounds?\b/gi, '边界'],
  [/\bground\b/gi, '地面'],
  [/\bturn\b/gi, '回合'],
  [/\bsmoky\b/gi, '烟雾'],
  [/\binsatiable\b/gi, '永不满足'],
  [/\bmagnet\b/gi, '磁铁'],
  [/\bphysically\b/gi, '物理上'],
  [/\brather\b/gi, '而是'],
  [/\bpicking\b/gi, '选取'],
  [/\bones\b/gi, '的'],
  [/\bnormally\b/gi, '通常'],
  [/\bplaying\b/gi, '游玩'],
  [/\baround\b/gi, '周围'],
  [/\binside\b/gi, '内部'],
  [/\boutside\b/gi, '外部'],
  [/\bbeen\b/gi, '已'],
  [/\bups\b/gi, '升级'],

  // --- ultimate catch batch ---
  // Game system terms
  [/\bPoe\b/g, '坡'],
  [/\bJonathan\b/g, '乔纳森'],
  [/\bElizabeth\b/g, '伊丽莎白'],
  [/\bCustos\b/g, '库斯托斯'],
  [/\bBanished\b/g, '放逐'],
  [/\bCastlevania\b/g, '恶魔城'],
  [/\bAwake\b/g, '觉醒'],
  [/\bPinthot\b/g, '品索'],
  [/\bPowerups?\b/g, '强化道具'],
  [/\bBoss\b/g, 'Boss'],
  [/\bBosses?\b/g, 'Boss'],
  [/\bOde\b/g, '颂歌'],

  // Verbs/actions
  [/\bbar\b/gi, '条'],
  [/\bbypasses?\b/gi, '绕过'],
  [/\bincludes?\b/gi, '包括'],
  [/\braised\b/gi, '提升'],
  [/\breturn\b/gi, '返还'],
  [/\bspend\b/gi, '消耗'],
  [/\bspends\b/gi, '消耗'],
  [/\bgranting\b/gi, '授予'],
  [/\bselecting\b/gi, '选择'],
  [/\bgaining\b/gi, '获得'],
  [/\bconnected\b/gi, '连接'],
  [/\bEntering\b/gi, '进入'],
  [/\bdespawns?\b/gi, '消失'],
  [/\bserves?\b/gi, '充当'],
  [/\bsurrounding\b/gi, '周围'],
  [/\bacquiring\b/gi, '获得'],
  [/\bmorphs?\b/gi, '变形'],
  [/\bdying\b/gi, '死亡'],
  [/\bdoubled\b/gi, '翻倍'],
  [/\bcovers?\b/gi, '覆盖'],
  [/\bIncreasing\b/gi, '增加'],
  [/\bhalves?\b/gi, '减半'],
  [/\bdisables?\b/gi, '禁用'],
  [/\bcarry\b/gi, '携带'],
  [/\bunlocked\b/gi, '解锁'],
  [/\bstop\b/gi, '停止'],
  [/\bturned\b/gi, '开启'],

  // Nouns
  [/\bteammates?\b/gi, '队友'],
  [/\bmultiplayer\b/gi, '多人游戏'],
  [/\bconversion\b/gi, '转换'],
  [/\bGrowth\b/gi, '成长'],
  [/\bcharacter\b/gi, '角色'],
  [/\bcharacters?\b/gi, '角色'],
  [/\bpercentage\b/gi, '百分比'],
  [/\binstances\b/gi, '实例'],
  [/\bstaircases?\b/gi, '楼梯'],
  [/\bcutscene\b/gi, '过场'],
  [/\bprelude\b/gi, '前奏'],
  [/\bbattle\b/gi, '战斗'],
  [/\bretaliation\b/gi, '反击'],
  [/\bkills\b/gi, '击杀'],
  [/\bplayers?\b/gi, '玩家'],
  [/\bfirebreathing\b/gi, '喷火'],
  [/\bissue\b/gi, '问题'],
  [/\bbeginning\b/gi, '开始'],
  [/\bmatter\b/gi, '关系'],

  // Adjectives/adverbs
  [/\bwell\b/gi, '好'],
  [/\beven\b/gi, '即使'],
  [/\bAlthough\b/gi, '虽然'],
  [/\banyone\b/gi, '任何人'],
  [/\bunaffected\b/gi, '不受影响'],
  [/\brepeatedly\b/gi, '反复'],
  [/\bpotential\b/gi, '潜在'],
  [/\bDespite\b/gi, '尽管'],
  [/\bwording\b/gi, '措辞'],
  [/\balong\b/gi, '随'],
  [/\bvalid\b/gi, '有效'],
  [/\badditively\b/gi, '累加地'],
  [/\bwhichever\b/gi, '取其低者'],
  [/\bincoming\b/gi, '来袭'],
  [/\balbeit\b/gi, '尽管'],
  [/\bsubject\b/gi, '受制于'],
  [/\bdecay\b/gi, '衰减'],
  [/\bpowerful\b/gi, '强大'],
  [/\bexact\b/gi, '完全'],
  [/\brequired\b/gi, '需要'],
  [/\bcritically\b/gi, '严重'],
  [/\bmuch\b/gi, '很'],
  [/\bcurrently\b/gi, '当前'],
  [/\bguaranteed\b/gi, '必定'],
  [/\bcapped\b/gi, '有上限'],
  [/\bmeaning\b/gi, '意味着'],
  [/\battacks?\b/gi, '攻击'],
  [/\bhas\b/gi, '有'],

  // Directional/quantifiers
  [/\ball\b/gi, '所有'],
  [/\bsix\b/gi, '六'],
  [/\bfinal\b/gi, '最终'],
  [/\bexception\b/gi, '例外'],

  // Cleanup
  [/\s+that\b/gi, ''],
  [/\s+is\b/gi, ''],
  [/['\u2019]s/gi, '的'],
  [/，\s*，/g, '，'],
  [/。\s*。/g, '。'],
  [/\s{2,}/g, ' '],
];

function translateText(text) {
  let result = text;
  for (const [pattern, replacement] of fieldReplacements) {
    result = result.replace(pattern, replacement);
  }
  return result;
}

let totalReplacements = 0;

// Process passiveDesc
data = data.replace(/passiveDesc:\s*"([^"]*)"/g, (match, text) => {
  const translated = translateText(text);
  if (text !== translated) totalReplacements++;
  return `passiveDesc: "${translated}"`;
});

// Process unlock
data = data.replace(/unlock:\s*"([^"]*)"/g, (match, text) => {
  const translated = translateText(text);
  if (text !== translated) totalReplacements++;
  return `unlock: "${translated}"`;
});

fs.writeFileSync(filePath, data, "utf-8");
console.log(`Fields modified: ${totalReplacements}`);

// Count remaining English
const re = /passiveDesc:\s*"([^"]*)"/g;
let m, eng = 0, total = 0;
while ((m = re.exec(data)) !== null) {
  total++;
  if (/[a-zA-Z]{4,}/.test(m[1])) eng++;
}
console.log(`passiveDesc with English: ${eng}/${total}`);
